# Changelog

# ⚠⚠ Please follow the format provided ⚠⚠
#  - name: version number
#    changes:
#      - title: Title of changes
#        categories: [CHANGED AREA]
#        authors: [YourName]


releases:

  - name: 1.0.0
    changes:
      - title: Initial Release
        categories: [Core]
        authors: [Jayther]
